experiment-name: leela93-dfrc99-filt-only-T80octnov
training-dataset: /root/training-data/leela93-dfrc99-filt-only-T80octnov.binpack
nnue-pytorch-branch: linrock/nnue-pytorch/misc-fixes

early-fen-skipping: 28
num-epochs: 800
start-lambda: 1.0
end-lambda: 0.7
network-testing-games-per-round: 1000
network-testing-threads: 24
num-workers: 6
start-from-engine-test-net: True

lr: 4.375e-4
gamma: 0.995

build-engine-arch: x86-64-bmi2
workspace-path: /root/easy-train-data
gpus: $(filename_to_gpu_str)
nnue-pytorch-branch: $nnue_pytorch_branch
